nodes:
  - nodeId: "node1"
    nodeType: "DATA_FETCH"
    behaviours:
      - type: "DataFetcher"
        config:
          sourceType: "API"
          endpoint: "https://financialmodelingprep.com/api/v3/profile/AAPL"
          timeout: 10
          headers:
            Content-Type: "application/json"
          params:
            apikey: "YQo7qP2o3Rd3CjjgQ84nPh31uJUdklQi"
    connections:
      - targetNodeId: "node2"
        type: "DIRECT"

  - nodeId: "node2"
    nodeType: "LLM"
    behaviours:
      - type: "LLMProcessor"
        config:
          modelType: "openai"
          model: "gpt-4o-mini"
          promptTemplate: "detailed_analysis"
          instructions: "Generate a report from the following data."
    connections: [] # No outgoing connections
