nodes:
  - nodeId: "node1"
    nodeType: "DATA_FETCH"
    behaviours:
      - type: "DataFetcher"
        config:
          sourceType: "API"
          endpoint: "https://financialmodelingprep.com/api/v3/profile/AAPL"
          timeout: 10
          headers:
            Content-Type: "application/json"
          params:
            apikey: "YQo7qP2o3Rd3CjjgQ84nPh31uJUdklQi"

  - nodeId: "node2"
    nodeType: "DATA_FETCH"
    behaviours:
      - type: "DataFetcher"
        config:
          sourceType: "Database"
          connectionString: "jdbc:mysql://localhost:3306/mydb"

  - nodeId: "node3"
    nodeType: "DATA_FETCH"
    behaviours:
      - type: "DataFetcher"
        config:
          sourceType: "API"
          endpoint: "https://financialmodelingprep.com/api/v3/quote/AAPL"
          timeout: 10
          headers:
            Content-Type: "application/json"
          params:
            apikey: "YQo7qP2o3Rd3CjjgQ84nPh31uJUdklQi"

  - nodeId: "node4"
    nodeType: "DATA_FETCH"
    behaviours:
      - type: "DataFetcher"
        config:
          sourceType: "API"
          endpoint: "https://financialmodelingprep.com/api/v3/key-metrics/AAPL"
          timeout: 10
          headers:
            Content-Type: "application/json"
          params:
            apikey: "YQo7qP2o3Rd3CjjgQ84nPh31uJUdklQi"

  - nodeId: "node5"
    nodeType: "LLM"
    behaviours:
      - type: "LLMProcessor"
        config:
          modelType: "openai"
          inputSource:
            - "node1"
            - "node3"
