nodes:
  # Data Source 1
  - nodeId: "data_source_1"
    nodeType: "DATA_FETCH"
    behaviours:
      - type: "DataFetcher"
        config:
          sourceType: "API"
          endpoint: "https://financialmodelingprep.com/api/v3/key-metrics/AAPL"
          timeout: 10
          headers:
            Content-Type: "application/json"
          params:
            apikey: "YQo7qP2o3Rd3CjjgQ84nPh31uJUdklQi"
    connections:
      - targetNodeId: "llm_processor_1"
        type: "DIRECT"

  # LLM Processor 1 - Initial Analysis
  - nodeId: "llm_processor_1"
    nodeType: "LLM"
    behaviours:
      - type: "LLMProcessor"
        config:
          modelType: "openai"
          model: "gpt-4o-mini"
          promptTemplate: "summary_analysis"
          instructions: "Provide a high-level summary and key takeaways from the provided financial metrics data."
    connections:
      - targetNodeId: "llm_processor_2"
        type: "DIRECT"

  # Data Source 2
  - nodeId: "data_source_2"
    nodeType: "DATA_FETCH"
    behaviours:
      - type: "DataFetcher"
        config:
          sourceType: "API"
          endpoint: "https://financialmodelingprep.com/api/v3/profile/AAPL"
          timeout: 10
          headers:
            Content-Type: "application/json"
          params:
            apikey: "YQo7qP2o3Rd3CjjgQ84nPh31uJUdklQi"
    connections:
      - targetNodeId: "llm_processor_2"
        type: "DIRECT"

  # LLM Processor 2 - Comparative Analysis with Additional Data
  - nodeId: "llm_processor_2"
    nodeType: "LLM"
    behaviours:
      - type: "LLMProcessor"
        config:
          modelType: "openai"
          model: "gpt-4o-mini"
          promptTemplate: "comparative_analysis"
          instructions: "Combine the summary from LLM 1 with profile data from Data Source 2 to perform a detailed comparative analysis, focusing on trends and strategic implications."
    connections: []
