nodes:
  # Data Fetch Nodes for each stock
  - nodeId: "data_fetch_stock1"
    nodeType: "DATA_FETCH"
    behaviours:
      - type: "DataFetcher"
        config:
          sourceType: "API"
          endpoint: "https://financialmodelingprep.com/api/v3/key-metrics/GOOGL"
          timeout: 10
          headers:
            Content-Type: "application/json"
          params:
            apikey: "YQo7qP2o3Rd3CjjgQ84nPh31uJUdklQi"
    connections:
      - targetNodeId: "analysis_stock1"
        type: "DIRECT"

  - nodeId: "data_fetch_stock2"
    nodeType: "DATA_FETCH"
    behaviours:
      - type: "DataFetcher"
        config:
          sourceType: "API"
          endpoint: "https://financialmodelingprep.com/api/v3/key-metrics/AMZN"
          timeout: 10
          headers:
            Content-Type: "application/json"
          params:
            apikey: "YQo7qP2o3Rd3CjjgQ84nPh31uJUdklQi"
    connections:
      - targetNodeId: "analysis_stock2"
        type: "DIRECT"

  - nodeId: "data_fetch_stock3"
    nodeType: "DATA_FETCH"
    behaviours:
      - type: "DataFetcher"
        config:
          sourceType: "API"
          endpoint: "https://financialmodelingprep.com/api/v3/key-metrics/FB"
          timeout: 10
          headers:
            Content-Type: "application/json"
          params:
            apikey: "YQo7qP2o3Rd3CjjgQ84nPh31uJUdklQi"
    connections:
      - targetNodeId: "analysis_stock3"
        type: "DIRECT"

  # LLM Nodes for Individual Analysis for each stock
  - nodeId: "analysis_stock1"
    nodeType: "LLM"
    behaviours:
      - type: "LLMProcessor"
        config:
          modelType: "openai"
          model: "gpt-4o-mini"
          promptTemplate: "detailed_analysis"
          instructions: "Analyze financial metrics for GOOGL."
    connections:
      - targetNodeId: "combined_analysis"
        type: "DIRECT"

  - nodeId: "analysis_stock2"
    nodeType: "LLM"
    behaviours:
      - type: "LLMProcessor"
        config:
          modelType: "openai"
          model: "gpt-4o-mini"
          promptTemplate: "detailed_analysis"
          instructions: "Analyze financial metrics for AMZN."
    connections:
      - targetNodeId: "combined_analysis"
        type: "DIRECT"

  - nodeId: "analysis_stock3"
    nodeType: "LLM"
    behaviours:
      - type: "LLMProcessor"
        config:
          modelType: "openai"
          model: "gpt-4o-mini"
          promptTemplate: "detailed_analysis"
          instructions: "Analyze financial metrics for FB."
    connections:
      - targetNodeId: "detailed_analysis"
        type: "DIRECT"

  # Converging LLM Node to Aggregate Analysis
  - nodeId: "combined_analysis"
    nodeType: "LLM"
    behaviours:
      - type: "LLMProcessor"
        config:
          modelType: "openai"
          model: "gpt-4o-mini"
          promptTemplate: "combined_summary"
          instructions: "Combine analysis insights from GOOGL, AMZN, and FB."
    connections:
      - targetNodeId: "final_recommendation"
        type: "DIRECT"

  # Final LLM Node for Recommendation
  - nodeId: "final_recommendation"
    nodeType: "LLM"
    behaviours:
      - type: "LLMProcessor"
        config:
          modelType: "openai"
          model: "gpt-4o-mini"
          promptTemplate: "default"
          instructions: "Based on the combined analysis, provide a final buy, sell or  hold recommendation."
    connections: []
